// <auto-generated />
using System.Resources;
using System.Globalization;

namespace WarcraftBattle.Editor.Properties
{
    internal static class Strings
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        internal static ResourceManager ResourceManager => resourceMan ??= new ResourceManager("WarcraftBattle.Editor.Properties.Strings", typeof(Strings).Assembly);

        internal static CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string EditorTitle => ResourceManager.GetString("EditorTitle", resourceCulture)!;
        internal static string MenuFile => ResourceManager.GetString("MenuFile", resourceCulture)!;
        internal static string MenuNew => ResourceManager.GetString("MenuNew", resourceCulture)!;
        internal static string MenuOpen => ResourceManager.GetString("MenuOpen", resourceCulture)!;
        internal static string MenuSave => ResourceManager.GetString("MenuSave", resourceCulture)!;
        internal static string MenuSaveAs => ResourceManager.GetString("MenuSaveAs", resourceCulture)!;
        internal static string MenuExport => ResourceManager.GetString("MenuExport", resourceCulture)!;
        internal static string MenuEdit => ResourceManager.GetString("MenuEdit", resourceCulture)!;
        internal static string MenuUndo => ResourceManager.GetString("MenuUndo", resourceCulture)!;
        internal static string MenuRedo => ResourceManager.GetString("MenuRedo", resourceCulture)!;
        internal static string MenuCut => ResourceManager.GetString("MenuCut", resourceCulture)!;
        internal static string MenuCopy => ResourceManager.GetString("MenuCopy", resourceCulture)!;
        internal static string MenuPaste => ResourceManager.GetString("MenuPaste", resourceCulture)!;
        internal static string MenuView => ResourceManager.GetString("MenuView", resourceCulture)!;
        internal static string MenuShowToolbox => ResourceManager.GetString("MenuShowToolbox", resourceCulture)!;
        internal static string MenuShowInspector => ResourceManager.GetString("MenuShowInspector", resourceCulture)!;
        internal static string MenuShowOutput => ResourceManager.GetString("MenuShowOutput", resourceCulture)!;
        internal static string MenuData => ResourceManager.GetString("MenuData", resourceCulture)!;
        internal static string MenuObjectEditor => ResourceManager.GetString("MenuObjectEditor", resourceCulture)!;
        internal static string MenuTriggerEditor => ResourceManager.GetString("MenuTriggerEditor", resourceCulture)!;
        internal static string MenuEnvironment => ResourceManager.GetString("MenuEnvironment", resourceCulture)!;
        internal static string StatusReady => ResourceManager.GetString("StatusReady", resourceCulture)!;
        internal static string ToolboxPalette => ResourceManager.GetString("ToolboxPalette", resourceCulture)!;
        internal static string ToolboxAssets => ResourceManager.GetString("ToolboxAssets", resourceCulture)!;
        internal static string AssetBrowserPlaceholder => ResourceManager.GetString("AssetBrowserPlaceholder", resourceCulture)!;
        internal static string PlacementMode => ResourceManager.GetString("PlacementMode", resourceCulture)!;
        internal static string ModeSelect => ResourceManager.GetString("ModeSelect", resourceCulture)!;
        internal static string ModeBuilding => ResourceManager.GetString("ModeBuilding", resourceCulture)!;
        internal static string ModeObstacle => ResourceManager.GetString("ModeObstacle", resourceCulture)!;
        internal static string BuildingList => ResourceManager.GetString("BuildingList", resourceCulture)!;
        internal static string Team => ResourceManager.GetString("Team", resourceCulture)!;
        internal static string ObstacleList => ResourceManager.GetString("ObstacleList", resourceCulture)!;
        internal static string StageSettings => ResourceManager.GetString("StageSettings", resourceCulture)!;
        internal static string StageSelect => ResourceManager.GetString("StageSelect", resourceCulture)!;
        internal static string StageTitle => ResourceManager.GetString("StageTitle", resourceCulture)!;
        internal static string StageWidth => ResourceManager.GetString("StageWidth", resourceCulture)!;
        internal static string StageHeight => ResourceManager.GetString("StageHeight", resourceCulture)!;
        internal static string StageEnemyHp => ResourceManager.GetString("StageEnemyHp", resourceCulture)!;
        internal static string StageObstacleCount => ResourceManager.GetString("StageObstacleCount", resourceCulture)!;
        internal static string ApplyStageSettings => ResourceManager.GetString("ApplyStageSettings", resourceCulture)!;
        internal static string SelectionTools => ResourceManager.GetString("SelectionTools", resourceCulture)!;
        internal static string DeleteSelection => ResourceManager.GetString("DeleteSelection", resourceCulture)!;
        internal static string SaveMap => ResourceManager.GetString("SaveMap", resourceCulture)!;
        internal static string OutputTitle => ResourceManager.GetString("OutputTitle", resourceCulture)!;
        internal static string StageUpdatedFormat => ResourceManager.GetString("StageUpdatedFormat", resourceCulture)!;
        internal static string GameConfigMissing => ResourceManager.GetString("GameConfigMissing", resourceCulture)!;
        internal static string SaveCompleteFormat => ResourceManager.GetString("SaveCompleteFormat", resourceCulture)!;
    }
}
